meta_product_name: ""
meta_title: ""
meta_description: " is the best product in the market"
meta_image: "cover.png"
twitter_account: "@product_twitter_account"
company_name: "Internl"
company_website: "https://internl.de"
company_twitter: ""
setup_date: "Tue Mar 25 19:15:07 CET 2025"
